# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-12 13:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('type', models.IntegerField(choices=[(0, '原创'), (1, '转载'), (2, '翻译'), (3, '其他')], verbose_name='类型')),
                ('article', models.TextField(max_length=5000, verbose_name='正文')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='最后一次更新')),
            ],
            options={
                'verbose_name': '博文',
                'verbose_name_plural': '博文',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=30, verbose_name='用户名')),
                ('user_email', models.EmailField(max_length=30, verbose_name='邮箱')),
                ('user_password', models.CharField(max_length=12, verbose_name='用户密码')),
                ('user_type', models.IntegerField(choices=[(0, '普通用户'), (1, '管理员'), (2, '超级管理员'), (3, '站长')], default=0)),
                ('user_register_time', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gufeng.User', verbose_name='作者'),
        ),
        migrations.AddField(
            model_name='article',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gufeng.Tag', verbose_name='标签'),
        ),
    ]
