# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-12 14:51
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gufeng', '0002_auto_20180212_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=5000, verbose_name='正文'),
        ),
    ]
