# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-13 08:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gufeng', '0004_article_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='FootInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('powerby', models.CharField(default='过不去的过去', max_length=100, verbose_name='版权')),
                ('Register_Id', models.CharField(default='豫ICP备17028946号', max_length=100, verbose_name='备案号')),
                ('Design_By', models.CharField(default='过不去的过去', max_length=100, verbose_name='设计者')),
            ],
            options={
                'verbose_name': '版权',
                'verbose_name_plural': '版权',
                'ordering': ['id'],
            },
        ),
    ]
