# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-14 02:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gufeng', '0005_footinfo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-update_date'], 'verbose_name': '博文', 'verbose_name_plural': '博文'},
        ),
        migrations.AlterModelOptions(
            name='footinfo',
            options={'ordering': ['-id'], 'verbose_name': '版权', 'verbose_name_plural': '版权'},
        ),
    ]
