# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-14 07:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gufeng', '0006_auto_20180214_1008'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavigationBar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='标题')),
                ('link', models.CharField(max_length=200, verbose_name='链接')),
                ('have_second_bar', models.BooleanField(default=False, verbose_name='是否有二级菜单')),
            ],
            options={
                'verbose_name': '导航栏设置',
                'verbose_name_plural': '导航栏设置',
            },
        ),
        migrations.CreateModel(
            name='SecondNavigationBar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('second_tile', models.CharField(blank=True, max_length=30, null=True, verbose_name='二级标题')),
                ('second_link', models.CharField(blank=True, max_length=200, null=True, verbose_name='二级链接')),
                ('NavigationBar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gufeng.NavigationBar')),
            ],
            options={
                'verbose_name': '二级导航栏设置',
                'verbose_name_plural': '二级导航栏设置',
            },
        ),
    ]
