# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-14 07:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gufeng', '0007_navigationbar_secondnavigationbar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='secondnavigationbar',
            old_name='second_tile',
            new_name='second_title',
        ),
    ]
